### ISSUE TITLE
Unable to Use Latest version of .netcore

### ISSUE THREAD

**Issue by tobilap** [lukasz-pyrzyk/XGain#5]
Is there any way you could remove the Experimental reference from the NuGet package?

" Unable to resolve 'System.Buffers.Experimental (>= 0.1.0-e160527-1)' for '.NETCoreApp,Version=v1.0'."

**Comment by lukasz-pyrzyk** [comment]
Hello @tobilap,

thanks for submitting issue. I will update XGain to the latest version of .NET Core this week.

**Comment by lukasz-pyrzyk** [comment]
Hi again @tobilap,

I've published new versoin 1.2.0. It supports the latest version of .NET Core.
Could you please verify again?

**Comment by tobilap** [comment]
Thanks a lot, works fine now :)
